In [1]:
import pandas as pd #
import numpy as np
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from scipy.stats import zscore

csv_path = "./data_raw/merged_data.csv"
#device = "103"
#save_path = f"./data/dev{device}_prepared.csv"
save_path = f"./dataMA/merged_data_prepared.csv"

df = pd.read_csv(csv_path)

In [2]:
df.head()

,timestamp,devID,soil,rain,temp,humi,geo,lat,lng,iso_score,...,rain_ma_24h,soil_ma_4h,soil_ma_8h,soil_ma_12h,soil_ma_16h,geo_ma_2min,geo_ma_4min,geo_ma_6min,geo_ma_8min,label
0,2025-11-01 06:33:49.988,108,0.000000,0.0,34.000000,66.500000,0.0,0.0,0.0,0.029171,...,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN
1,2025-11-01 06:34:28.395,108,0.000000,0.0,34.000000,66.500000,0.0,0.0,0.0,0.029171,...,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,NaN
2,2025-11-01 06:35:13.489,108,0.798555,0.0,34.049999,66.650002,0.0,-1.0,-1.0,0.029812,...,0.0,0.266185,0.266185,0.266185,0.266185,0.0,0.0,0.0,0.0,NaN
3,2025-11-01 06:35:33.224,108,0.000000,0.0,34.200001,67.900002,0.0,0.0,0.0,0.032640,...,0.0,0.199639,0.199639,0.199639,0.199639,0.0,0.0,0.0,0.0,NaN
4,2025-11-01 06:36:11.416,108,0.000000,0.0,34.200001,67.900002,0.0,0.0,0.0,0.032640,...,0.0,0.159711,0.159711,0.159711,0.159711,0.0,0.0,0.0,0.0,NaN

In [5]:
#df['devID'] = df['หมายเลขอุปกรณ์']
#df.drop(columns=['หมายเลขอุปกรณ์', "ชื่อสถานี", "ละติจูด", "ลองจิจูด", "ระดับความเสี่ยง", "ISO Risk", "LSTM Risk", "RF Risk"], inplace=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46130 entries, 0 to 46129
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    46130 non-null  object
 1   devID        46130 non-null  int64
 2   soil         46130 non-null  float64
 3   rain         46130 non-null  float64
 4   temp         46130 non-null  float64
 5   humi         46130 non-null  float64
 6   geo          46130 non-null  float64
 7   lat          46130 non-null  float64
 8   lng          46130 non-null  float64
 9   iso_score    46130 non-null  float64
 10  iso_risk     46130 non-null  int64
 11  lstm_score   46130 non-null  float64
 12  lstm_risk    46130 non-null  int64
 13  confidence   46130 non-null  float64
 14  geo.1        46128 non-null  float64
 15  rain_ma_1h   46128 non-null  float64
 16  rain_ma_6h   46128 non-null  float64
 17  rain_ma_12h  46128 non-null  float64
 18  rain_ma_24h  46128 non-null  float64
 19  soil_ma_4h   46128 non-null  float64
 20  soil_ma_8h   46128 non-null  float64
 21  soil_ma_12h  46128 non-null  float64
 22  soil_ma_16h  46128 non-null  float64
 23  geo_ma_2min  46128 non-null  float64
 24  geo_ma_4min  46128 non-null  float64
 25  geo_ma_6min  46128 non-null  float64
 26  geo_ma_8min  46128 non-null  float64
 27  label        442 non-null    object
dtypes: float64(23), int64(3), object(2)
memory usage: 9.9+ MB

In [6]:
df.describe()

,devID,soil,rain,temp,humi,geo,lat,lng,iso_score,iso_risk,...,rain_ma_12h,rain_ma_24h,soil_ma_4h,soil_ma_8h,soil_ma_12h,soil_ma_16h,geo_ma_2min,geo_ma_4min,geo_ma_6min,geo_ma_8min
count,46130.000000,46130.000000,46130.000000,46130.000000,46130.000000,46130.000000,46130.000000,46130.000000,46130.000000,46130.000000,...,46128.000000,46128.000000,46128.000000,46128.000000,46128.000000,46128.000000,46128.000000,46128.000000,46128.000000,46128.000000
mean,107.251745,36.257275,0.181341,27.201526,85.146806,5.803860,9.476938,102.411321,0.060265,0.044310,...,0.181807,0.168620,36.134036,35.991561,35.826856,35.707292,5.804661,5.808856,5.812268,5.804964
std,1.432138,6.593057,1.603585,3.913018,12.679680,9.463432,75.705032,309.794428,0.050444,0.248014,...,0.547086,0.374379,4.236562,4.298773,4.276901,4.221227,4.294375,3.564129,3.238230,3.029463
min,104.000000,0.000000,-1.000000,0.000000,0.000000,-352.257019,-1.000000,-1.000000,-0.193431,0.000000,...,-0.061224,-0.061224,0.000000,0.000000,0.000000,0.000000,-22.943130,-11.745900,-6.232689,-3.427309
25%,106.000000,32.700001,0.000000,24.100000,76.550003,0.385935,8.866826,99.749573,0.034917,0.000000,...,0.000000,0.000000,33.686400,33.710096,33.691931,33.551257,2.848528,3.460856,3.721737,3.887824
50%,107.000000,36.500000,0.000000,25.600000,89.500000,0.640136,8.868596,99.754532,0.057214,0.000000,...,0.006131,0.009935,35.421065,35.408591,35.453830,35.447344,5.029191,5.221212,5.243523,5.267385
75%,109.000000,41.400002,0.000000,30.400000,95.900002,9.783067,8.886639,99.784538,0.097251,0.000000,...,0.020747,0.068522,39.728071,39.625545,39.370656,38.972075,7.781774,7.316013,7.110596,6.950050
max,109.000000,62.099998,38.277802,38.400002,100.000000,542.780799,8138.283203,23593.232420,0.189302,2.000000,...,2.708392,1.278639,45.638325,43.778592,43.010041,42.359848,65.074634,36.870019,30.536604,30.536604

In [ ]:
#df['devID'] = df['devID'].str.replace('Node ', '', regex=False)

In [24]:
#df.drop(columns=['device'], inplace=True)

In [15]:
df["devID"] = df["device"]

In [7]:
for col in ['soil', 'rain', 'temp', 'humi', 'geo', 'devID']:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df

,timestamp,devID,soil,rain,temp,humi,geo,lat,lng,iso_score,...,rain_ma_24h,soil_ma_4h,soil_ma_8h,soil_ma_12h,soil_ma_16h,geo_ma_2min,geo_ma_4min,geo_ma_6min,geo_ma_8min,label
0,2025-11-01 06:33:49.988,108,0.000000,0.0,34.000000,66.500000,0.000000,0.000000,0.000000,0.029171,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
1,2025-11-01 06:34:28.395,108,0.000000,0.0,34.000000,66.500000,0.000000,0.000000,0.000000,0.029171,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
2,2025-11-01 06:35:13.489,108,0.798555,0.0,34.049999,66.650002,0.000000,-1.000000,-1.000000,0.029812,...,0.000000,0.266185,0.266185,0.266185,0.266185,0.000000,0.000000,0.000000,0.000000,NaN
3,2025-11-01 06:35:33.224,108,0.000000,0.0,34.200001,67.900002,0.000000,0.000000,0.000000,0.032640,...,0.000000,0.199639,0.199639,0.199639,0.199639,0.000000,0.000000,0.000000,0.000000,NaN
4,2025-11-01 06:36:11.416,108,0.000000,0.0,34.200001,67.900002,0.000000,0.000000,0.000000,0.032640,...,0.000000,0.159711,0.159711,0.159711,0.159711,0.000000,0.000000,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46125,2025-11-10 23:06:18.418,107,38.599998,0.0,22.799999,97.199997,0.785280,8.866687,99.754539,0.033331,...,0.259966,41.073920,41.242741,41.559293,40.054808,3.558571,5.463782,4.814836,5.626750,NaN
46126,2025-11-10 23:06:25.333,106,41.199999,0.0,23.500000,90.700001,0.684158,8.886681,99.784546,0.038469,...,0.259966,41.074007,41.242726,41.559206,40.055017,3.585020,5.477477,4.824122,5.633303,NaN
46127,2025-11-10 23:06:35.525,105,45.299999,0.0,23.600000,92.400002,0.441064,8.884858,99.783157,0.039357,...,0.259934,41.081198,41.246534,41.559230,40.055457,3.256141,4.458346,4.827885,5.531494,NaN
46128,2025-11-10 23:06:50.105,108,46.799999,0.0,22.799999,97.400002,15.691441,8.866831,99.754456,0.069070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46129,2025-11-10 23:06:53.723,109,34.700001,0.0,22.700001,95.199997,0.431964,8.868616,99.749542,0.033801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns = df.columns.str.strip()
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df = df.dropna(subset=['timestamp', 'geo'])

df = df[df['soil'] > 0]
df = df[df['rain'] >= 0]
df = df[df['humi'] > 0]
df = df[(df['geo'] >= 0) & (df['geo'] < 40)]
df = df[df['temp'] > 0]
df = df[(df['devID'] > 0) & (df['devID'] < 1000)]
df

,timestamp,devID,soil,rain,temp,humi,geo,lat,lng,iso_score,...,rain_ma_24h,soil_ma_4h,soil_ma_8h,soil_ma_12h,soil_ma_16h,geo_ma_2min,geo_ma_4min,geo_ma_6min,geo_ma_8min,label
2,2025-11-01 06:35:13.489,108,0.798555,0.0,34.049999,66.650002,0.000000,-1.000000,-1.000000,0.029812,...,0.000000,0.266185,0.266185,0.266185,0.266185,0.000000,0.000000,0.000000,0.000000,NaN
5,2025-11-01 06:36:31.666,108,0.534899,0.0,34.233334,67.233335,0.333333,-1.000000,-1.000000,0.035214,...,0.000000,0.222242,0.222242,0.222242,0.222242,0.083333,0.055556,0.055556,0.055556,NaN
9,2025-11-01 06:37:51.586,108,1.604698,0.0,34.250000,65.700001,1.000000,-1.000000,-1.000000,0.040288,...,0.000000,0.775225,0.775225,0.775225,0.775225,-0.277778,-0.185185,-0.166667,-0.166667,NaN
10,2025-11-01 06:42:51.995,108,1.604698,0.0,34.299999,61.299999,1.000000,8.873381,99.764809,0.034925,...,0.000000,0.850631,0.850631,0.850631,0.850631,1.000000,1.000000,0.000000,-0.074074,NaN
11,2025-11-01 06:43:52.076,108,1.604698,0.0,34.500000,60.700001,1.000000,8.872817,99.762062,0.030245,...,0.000000,0.913470,0.913470,0.913470,0.913470,1.000000,1.000000,1.000000,0.041667,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46125,2025-11-10 23:06:18.418,107,38.599998,0.0,22.799999,97.199997,0.785280,8.866687,99.754539,0.033331,...,0.259966,41.073920,41.242741,41.559293,40.054808,3.558571,5.463782,4.814836,5.626750,NaN
46126,2025-11-10 23:06:25.333,106,41.199999,0.0,23.500000,90.700001,0.684158,8.886681,99.784546,0.038469,...,0.259966,41.074007,41.242726,41.559206,40.055017,3.585020,5.477477,4.824122,5.633303,NaN
46127,2025-11-10 23:06:35.525,105,45.299999,0.0,23.600000,92.400002,0.441064,8.884858,99.783157,0.039357,...,0.259934,41.081198,41.246534,41.559230,40.055457,3.256141,4.458346,4.827885,5.531494,NaN
46128,2025-11-10 23:06:50.105,108,46.799999,0.0,22.799999,97.400002,15.691441,8.866831,99.754456,0.069070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46129,2025-11-10 23:06:53.723,109,34.700001,0.0,22.700001,95.199997,0.431964,8.868616,99.749542,0.033801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.columns = df.columns.str.strip()
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df = df.dropna(subset=['timestamp', 'geo'])  # ต้องมี timestamp และ geo

for col in ['soil', 'rain', 'temp', 'humi', 'geo']:

    df[col] = pd.to_numeric(df[col], errors='coerce')
df

,timestamp,devID,soil,rain,temp,humi,geo,lat,lng,iso_score,...,rain_ma_24h,soil_ma_4h,soil_ma_8h,soil_ma_12h,soil_ma_16h,geo_ma_2min,geo_ma_4min,geo_ma_6min,geo_ma_8min,label
2,2025-11-01 06:35:13.489,108,0.798555,0.0,34.049999,66.650002,0.000000,-1.000000,-1.000000,0.029812,...,0.000000,0.266185,0.266185,0.266185,0.266185,0.000000,0.000000,0.000000,0.000000,NaN
5,2025-11-01 06:36:31.666,108,0.534899,0.0,34.233334,67.233335,0.333333,-1.000000,-1.000000,0.035214,...,0.000000,0.222242,0.222242,0.222242,0.222242,0.083333,0.055556,0.055556,0.055556,NaN
9,2025-11-01 06:37:51.586,108,1.604698,0.0,34.250000,65.700001,1.000000,-1.000000,-1.000000,0.040288,...,0.000000,0.775225,0.775225,0.775225,0.775225,-0.277778,-0.185185,-0.166667,-0.166667,NaN
10,2025-11-01 06:42:51.995,108,1.604698,0.0,34.299999,61.299999,1.000000,8.873381,99.764809,0.034925,...,0.000000,0.850631,0.850631,0.850631,0.850631,1.000000,1.000000,0.000000,-0.074074,NaN
11,2025-11-01 06:43:52.076,108,1.604698,0.0,34.500000,60.700001,1.000000,8.872817,99.762062,0.030245,...,0.000000,0.913470,0.913470,0.913470,0.913470,1.000000,1.000000,1.000000,0.041667,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46125,2025-11-10 23:06:18.418,107,38.599998,0.0,22.799999,97.199997,0.785280,8.866687,99.754539,0.033331,...,0.259966,41.073920,41.242741,41.559293,40.054808,3.558571,5.463782,4.814836,5.626750,NaN
46126,2025-11-10 23:06:25.333,106,41.199999,0.0,23.500000,90.700001,0.684158,8.886681,99.784546,0.038469,...,0.259966,41.074007,41.242726,41.559206,40.055017,3.585020,5.477477,4.824122,5.633303,NaN
46127,2025-11-10 23:06:35.525,105,45.299999,0.0,23.600000,92.400002,0.441064,8.884858,99.783157,0.039357,...,0.259934,41.081198,41.246534,41.559230,40.055457,3.256141,4.458346,4.827885,5.531494,NaN
46128,2025-11-10 23:06:50.105,108,46.799999,0.0,22.799999,97.400002,15.691441,8.866831,99.754456,0.069070,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46129,2025-11-10 23:06:53.723,109,34.700001,0.0,22.700001,95.199997,0.431964,8.868616,99.749542,0.033801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.sort_values('timestamp').reset_index(drop=True)
df = df.set_index('timestamp')
df = df.reset_index()

In [11]:
df.head()

,timestamp,devID,soil,rain,temp,humi,geo,lat,lng,iso_score,...,rain_ma_24h,soil_ma_4h,soil_ma_8h,soil_ma_12h,soil_ma_16h,geo_ma_2min,geo_ma_4min,geo_ma_6min,geo_ma_8min,label
0,2025-11-01 06:35:13.489,108,0.798555,0.0,34.049999,66.650002,0.000000,-1.000000,-1.000000,0.029812,...,0.0,0.266185,0.266185,0.266185,0.266185,0.000000,0.000000,0.000000,0.000000,NaN
1,2025-11-01 06:36:31.666,108,0.534899,0.0,34.233334,67.233335,0.333333,-1.000000,-1.000000,0.035214,...,0.0,0.222242,0.222242,0.222242,0.222242,0.083333,0.055556,0.055556,0.055556,NaN
2,2025-11-01 06:37:51.586,108,1.604698,0.0,34.250000,65.700001,1.000000,-1.000000,-1.000000,0.040288,...,0.0,0.775225,0.775225,0.775225,0.775225,-0.277778,-0.185185,-0.166667,-0.166667,NaN
3,2025-11-01 06:42:51.995,108,1.604698,0.0,34.299999,61.299999,1.000000,8.873381,99.764809,0.034925,...,0.0,0.850631,0.850631,0.850631,0.850631,1.000000,1.000000,0.000000,-0.074074,NaN
4,2025-11-01 06:43:52.076,108,1.604698,0.0,34.500000,60.700001,1.000000,8.872817,99.762062,0.030245,...,0.0,0.913470,0.913470,0.913470,0.913470,1.000000,1.000000,1.000000,0.041667,NaN

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45824 entries, 0 to 45823
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    45824 non-null  datetime64[ns]
 1   devID        45824 non-null  int64
 2   soil         45824 non-null  float64
 3   rain         45824 non-null  float64
 4   temp         45824 non-null  float64
 5   humi         45824 non-null  float64
 6   geo          45824 non-null  float64
 7   lat          45824 non-null  float64
 8   lng          45824 non-null  float64
 9   iso_score    45824 non-null  float64
 10  iso_risk     45824 non-null  int64
 11  lstm_score   45824 non-null  float64
 12  lstm_risk    45824 non-null  int64
 13  confidence   45824 non-null  float64
 14  geo.1        45822 non-null  float64
 15  rain_ma_1h   45822 non-null  float64
 16  rain_ma_6h   45822 non-null  float64
 17  rain_ma_12h  45822 non-null  float64
 18  rain_ma_24h  45822 non-null  float64
 19  soil_ma_4h   45822 non-null  float64
 20  soil_ma_8h   45822 non-null  float64
 21  soil_ma_12h  45822 non-null  float64
 22  soil_ma_16h  45822 non-null  float64
 23  geo_ma_2min  45822 non-null  float64
 24  geo_ma_4min  45822 non-null  float64
 25  geo_ma_6min  45822 non-null  float64
 26  geo_ma_8min  45822 non-null  float64
 27  label        441 non-null    object
dtypes: datetime64[ns](1), float64(23), int64(3), object(1)
memory usage: 9.8+ MB

In [13]:
df.describe()

,timestamp,devID,soil,rain,temp,humi,geo,lat,lng,iso_score,...,rain_ma_12h,rain_ma_24h,soil_ma_4h,soil_ma_8h,soil_ma_12h,soil_ma_16h,geo_ma_2min,geo_ma_4min,geo_ma_6min,geo_ma_8min
count,45824,45824.000000,45824.000000,45824.000000,45824.000000,45824.000000,45824.000000,45824.000000,45824.000000,45824.000000,...,45822.000000,45822.000000,45822.000000,45822.000000,45822.000000,45822.000000,45822.000000,45822.000000,45822.000000,45822.000000
mean,2025-11-06 17:57:38.045280,107.255237,36.340472,0.184021,27.192051,85.217713,5.802921,9.492191,102.527804,0.060485,...,0.182480,0.169249,36.168626,36.022164,35.856117,35.736486,5.808219,5.814012,5.817213,5.810650
min,2025-11-01 06:35:13.489000,105.000000,0.534899,0.000000,16.450001,33.750000,0.000000,-1.000000,-1.000000,-0.193431,...,-0.060606,-0.060606,0.222242,0.222242,0.222242,0.222242,-22.943130,-11.745900,-6.232689,-3.415006
25%,2025-11-04 10:16:32.690999808,106.000000,32.700001,0.000000,24.100000,76.699997,0.388258,8.866826,99.749573,0.035020,...,0.000000,0.000000,33.690573,33.710761,33.691940,33.551313,2.857825,3.467252,3.727983,3.892983
50%,2025-11-06 20:56:12.287000064,107.000000,36.599998,0.000000,25.600000,89.599998,0.646674,8.868596,99.754532,0.057672,...,0.006407,0.009956,35.422323,35.410503,35.455729,35.448311,5.037986,5.224008,5.245627,5.273593
75%,2025-11-09 12:30:19.156249856,109.000000,41.400002,0.000000,30.349999,95.900002,9.841150,8.886639,99.784538,0.097348,...,0.020753,0.068537,39.732452,39.627906,39.381776,38.983020,7.786241,7.318404,7.112980,6.952048
max,2025-11-10 23:06:53.723000,109.000000,62.099998,38.277802,38.400002,100.000000,39.624933,8138.283203,23593.232420,0.189302,...,2.708392,1.278639,45.638325,43.778592,43.010041,42.359848,63.190784,36.870019,30.536604,30.536604
std,NaN,1.432404,6.367340,1.608222,3.869332,12.566405,8.435102,75.956571,310.778956,0.050340,...,0.548074,0.374946,4.121523,4.187488,4.166385,4.109994,4.258832,3.553977,3.231660,3.024910

In [14]:
df['devID'].value_counts()

devID
109    13556
106    13093
108     8347
107     5493
105     5335
Name: count, dtype: int64

In [15]:

df.to_csv(f"{save_path}", index=False)

print("✅ บันทึกเรียบร้อยแล้ว")

✅ บันทึกเรียบร้อยแล้ว